<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1583141506263' stop='1583141511365'>
    <name>API Testing</name>
    <title>API Testing</title>
    <test-cases>
        <test-case start='1583141506264' status='failed' stop='1583141507225'>
            <name>API:GET CALL @smoke</name>
            <title>API:GET CALL @smoke</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='6505865f-e8bf-4f2b-98d7-f33d99f93e8e-attachment.png' type='image/png' size='3249'/>
            </attachments>
            <failure>
                <message>Expected Object({ id: 57, accountNumber: 'VCA-OU-71', addressLine1: 'string', addressLine2: 'string', addressLine3: 'string', streetName: 'string', area: 'string', zipCode: 560098, country: 'string', createdOn: '2020-02-24T11:17:56.283', modifiedOn: '2020-02-24T11:15:29.823', isPrimary: false, isActive: true }) to equal 'VCA-OU-71'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (D:\Mars_VoyagerAPI\TestSuites\sampleTestCase.spec.js:68:40)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1583141507225' status='failed' stop='1583141509366'>
            <name>API:POST CALL @smoke</name>
            <title>API:POST CALL @smoke</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='2e91557e-515e-4c2c-807b-ca7b1e9be4b5-attachment.png' type='image/png' size='3249'/>
            </attachments>
            <failure>
                <message>Expected 'VCA-OU-169' to equal 'VCA-OU-71'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (D:\Mars_VoyagerAPI\TestSuites\sampleTestCase.spec.js:101:37)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1583141509366' status='passed' stop='1583141510455'>
            <name>API:PUT CALL @regression</name>
            <title>API:PUT CALL @regression</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='c915b4c6-0a22-4896-9d5e-4a16d96e5889-attachment.png' type='image/png' size='3249'/>
            </attachments>
        </test-case>
        <test-case start='1583141510455' status='failed' stop='1583141511365'>
            <name>API:GET CALL FOR NOTES @smoke</name>
            <title>API:GET CALL FOR NOTES @smoke</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='740b2d1d-4046-4b90-ad51-5ad1741b0b7f-attachment.png' type='image/png' size='3249'/>
            </attachments>
            <failure>
                <message>Expected Object({ id: 117, accountNumber: 'VCA-OU-72', createdBy: 'Manoj', updatedBy: null, note: 'This note is created' }) to equal 'VCA-OU-71'.</message>
                <stack-trace>Error: Failed expectation
                    at UserContext.&lt;anonymous> (D:\Mars_VoyagerAPI\TestSuites\sampleTestCase.spec.js:137:37)
                    at processTicksAndRejections (internal/process/task_queues.js:97:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>